name: AutoDoc
version: "2025.10.16"
license: "GPL-2.0-or-later"
date: 2025-10-16
description: |
    Generate documentation from GAP source code

authors:
    - name: Sebastian Gutsche
      url: https://algebra.mathematik.uni-siegen.de/gutsche/
    - name: Max Horn
      url: https://www.quendi.de/math

maintainers:
    - name: Sebastian Gutsche
      url: https://algebra.mathematik.uni-siegen.de/gutsche/
    - name: Max Horn
      url: https://www.quendi.de/math

contributors:
    - name: Mohamed Barakat
    - name: Markus Pfeiffer
    - name: Øystein Skartsæterhagen
    - name: Chris Wensley
    - name: Glen Whitney
    - name: Fabian Zickgraf

GAP: ">= 4.5"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.6.3"
      url: "https://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"

www: https://gap-packages.github.io/AutoDoc
readme: README.md
packageinfo: https://gap-packages.github.io/AutoDoc/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/AutoDoc/releases/download/v2025.10.16/AutoDoc-2025.10.16.tar.gz

abstract: |

status: deposited
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
keywords: |
    Automatic documentation, GAP, GAPDoc.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>GH25</span>]   <b class='BibAuthor'>Gutsche, S. and Horn, M.</b>,
     <i class='BibTitle'>AutoDoc, Generate documentation from GAP source code,
             Version 2025.10.16</i>
     (<span class='BibYear'>2025</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/AutoDoc">https://gap-packages.github.io/AutoDoc</a></span>.
    </p>
    

bibtex: |
    @misc{ AutoDoc,
      author =           {Gutsche, S. and Horn, M.},
      title =            {{AutoDoc},  {Generate  documentation  from  GAP source
                          code}, {V}ersion 2025.10.16},
      month =            {Oct},
      year =             {2025},
      note =             {GAP package},
      howpublished =     {\href         {https://gap-packages.github.io/AutoDoc}
                          {\texttt{https://gap\texttt{\symbol{45}}packages.github.io/}\discretionary
                          {}{}{}\texttt{AutoDoc}}},
      keywords =         {Automatic documentation, GAP, GAPDoc},
      printedkey =       {GH25}
    }

