# Paired Examples Test, chapter 1
#
# DO NOT EDIT THIS FILE - EDIT EXAMPLES IN THE SOURCE INSTEAD!
#
# This file has been generated by AutoDoc. It contains examples extracted from
# the package documentation. Each example is preceded by a comment which gives
# the name of a GAPDoc XML file and a line range from which the example were
# taken. Note that the XML file in turn may have been generated by AutoDoc
# from some other input.
#
gap> START_TEST("paired_examples_test01.tst");

# _Chapter_Examples_Chapter.xml:14-17
gap> comment_example_value := 2 + 3;
5

# _Chapter_Examples_Chapter.xml:19-22
gap> comment_alias_example := 3 + 4;
7

# _Chapter_Examples_Chapter.xml:24-27
gap> 10 - 3;
7

# _Chapter_Examples_Chapter.xml:29-32
gap> 6 * 7;
42

#
gap> STOP_TEST("paired_examples_test01.tst", 1);
